### PR TITLE
Misc rotation fixes

### LINKED ISSUE #95: Placement of certain M2s seems off
Waterfalls from Stonewrought Dam (`-4660.336900981519, -3325.714373498674, 296`)

screen shot 2016-01-09 at 21 50 53

Bridge leading to Stonewatch Keep (`-9542.955576414317, -2918.528868503445, 129.48000000000025`)

screen shot 2016-01-09 at 21 56 11

### PR DESCRIPTION
**Pull request by fallenoak**
This should fix the last of the known rotation issues, including those mentioned in #95.

### CODE REVIEW

File: src/lib/pipeline/wmo/index.js [hunk 1]
```diff
@@ -94,7 +94,9 @@ class WMO extends THREE.Group {
           entry.position.z
         );
 
-        m2.quaternion.copy(entry.rotation);
+        // Adjust M2 rotation to match Wowser's axes.
+        const quat = m2.quaternion;
+        quat.set(entry.rotation.x, entry.rotation.y, -entry.rotation.z, -entry.rotation.w);
```
Comment (timkurvers) [inline src/lib/pipeline/wmo/index.js]: :+1:

File: src/lib/game/world/map.js [hunk 2]
```diff
@@ -130,12 +130,17 @@ class WorldMap extends THREE.Group {
...
         entry.rotation.x * Math.PI / 180,
-        -entry.rotation.z * Math.PI / 180,
-        entry.rotation.y * Math.PI / 180
+        -entry.rotation.y * Math.PI / 180
       );
 
+      // Adjust M2 rotation to match Wowser's axes.
+      const quat = m2.quaternion;
+      quat.set(quat.x, quat.y, quat.z, -quat.w);
+
```
Comment (timkurvers) [inline src/lib/game/world/map.js]: Nice! :+1: 

Only thing I'm wondering about is whether it would be possible to calculate the quaternion only? Or do we need to go through Euler first?

THREE.js automatically converts that Euler rotation into a quaternion, here: https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L29-L41

Comment (fallenoak) [inline src/lib/game/world/map.js]: This works, but I'm not sure it's any more readable than what's listed above:

```
      // Provided as (Z, X, -Y) in degrees.
      const quat = m2.quaternion.setFromEuler(new THREE.Euler(
        entry.rotation.z * Math.PI / 180,
        entry.rotation.x * Math.PI / 180,
        -entry.rotation.y * Math.PI / 180
      ), false);

      // Adjust M2 rotation to match Wowser's axes.
      quat.set(quat.x, quat.y, quat.z, -quat.w);
```

Comment (timkurvers) [inline src/lib/game/world/map.js]: Ah yeah. No, I meant setting the quaternion directly, but I suppose it's the flipping of `w` that causes trouble, seeing as we don't know what to set it to?

Comment (timkurvers) [inline src/lib/game/world/map.js]: This is the most straight-forward way of adjusting the rotation to fit Wowser :+1:

**Comment by timkurvers** [comment]
Awesome stuff! :tada:
